/**
 * Speech provider interface for CogniCore's speech-gateway.
 *
 * All provider implementations must conform to this interface so that the
 * factory can swap them out based on the SPEECH_PROVIDER environment variable
 * without any changes to the consuming code.
 */

/** A single transcribed speech segment. */
export interface CaptionSegmentEvent {
  /** Unique identifier for this segment (generated by the provider or gateway). */
  id: string;
  /** The session this segment belongs to. */
  sessionId: string;
  /** The transcribed text (may be partial/interim if isFinal=false). */
  text: string;
  /** BCP-47 language tag, e.g. 'en-US', 'es-MX'. */
  language: string;
  /** Offset in seconds from the start of the audio stream. */
  startTime: number;
  /** End offset in seconds from the start of the audio stream. */
  endTime: number;
  /**
   * Whether this is a final, committed segment (true) or an interim
   * hypothesis subject to revision (false). Only final segments should
   * be persisted; interim segments flow through realtime only.
   */
  isFinal: boolean;
}

/**
 * Contract that every speech-to-text provider must implement.
 *
 * Providers are long-lived objects managed by the factory.  A single provider
 * instance may handle multiple concurrent sessions (each identified by
 * sessionId); implementations must maintain per-session state internally.
 */
export interface SpeechProvider {
  /** Human-readable name used in logs and metrics. */
  readonly name: string;

  /**
   * Begins streaming audio from the platform into the provider's STT engine
   * for the given session.
   *
   * @param sessionId  The CogniCore session identifier.
   * @param language   BCP-47 language tag for the primary recognition language.
   */
  startTranscription(sessionId: string, language: string): Promise<void>;

  /**
   * Stops the active transcription stream for a session and releases any
   * provider-side resources (websocket connections, audio buffers, etc.).
   *
   * @param sessionId  The CogniCore session identifier.
   */
  stopTranscription(sessionId: string): Promise<void>;

  /**
   * Registers a callback that is invoked whenever a caption segment
   * (interim or final) is received from the STT engine.
   *
   * Multiple handlers may be registered; each will receive every segment.
   *
   * @param handler  Callback invoked with each caption segment.
   */
  onSegment(handler: (segment: CaptionSegmentEvent) => void): void;

  /**
   * Feeds raw audio data into the provider for a specific session.
   * The format of `audioChunk` depends on the provider configuration
   * (PCM 16-bit, Opus, etc.).
   *
   * TODO: Standardise the audio format across providers (WebM/Opus from browser
   *       MediaRecorder → transcode to PCM via FFmpeg before handing to provider).
   *
   * @param sessionId  The CogniCore session identifier.
   * @param audioChunk Raw audio bytes.
   */
  pushAudio?(sessionId: string, audioChunk: Buffer): Promise<void>;
}
